username = input("Введите имя: ")
title = input("Введите заголовок: ")
content = input("Введите описание: ")
status = input("Введите статус заметки: ")
created_date = input("Введите Дату создания в формате день, месяц ,год (10-10-2000): ")
issue_date = input("Введите Дату истечения заметки в формате день, месяц ,год (10-10-2000): ")

print("Имя пользователя:", username)
print("Заголовок:", title)
print("Описание:", content)
print("Статус:", status)
print("Дата создания:", created_date)
print("Дата истечения заметки:", issue_date)